# 100 numpy exercises



File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
#%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__, np.__config__)
np.show_config()

1.20.2 <module 'numpy.__config__' from '/home/tonyalpha/.local/lib/python3.8/site-packages/numpy/__config__.py'>
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
x = np.zeros((10))
print(x.itemsize * x.size) # в байтах

80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
v = np.zeros(10)
v[4] = 1
print(v)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
v = np.arange(10,50)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
v[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
np.arange(9).reshape(3, -1)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
np.random.random((3,3,3))

array([[[0.92254305, 0.79078698, 0.23851707],
        [0.84088675, 0.96112385, 0.67356008],
        [0.09524189, 0.14720229, 0.80005712]],

       [[0.65433537, 0.46417358, 0.10842455],
        [0.32347651, 0.29706057, 0.2508182 ],
        [0.50451792, 0.37786687, 0.35532298]],

       [[0.76947461, 0.85400719, 0.51619723],
        [0.59081649, 0.7514463 , 0.14186247],
        [0.41427014, 0.7589288 , 0.85035431]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
arr = np.random.random((10,10))
print(arr.min(), arr.max())

0.007978441217360799 0.9894008629416499


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
arr = np.random.random(30)
print(arr.mean())

0.4827068309040699


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
n = 4
arr = np.zeros((n, n))
arr[0:, 0] = 1   
arr[0:, -1] = 1
arr[0, 0:] = 1
arr[-1, 0:] = 1
arr

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
np.pad(np.ones((4,4)), pad_width=1)

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan
False
False
nan
False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
print(np.diag(np.arange(1, 5))) # на диагонали ток размерность меньше будет очев
print(np.diag(np.arange(1, 5),k=-1)) # под
print(np.diag(np.arange(1, 5),k=1)) # над

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
np.tile(np.array([[0,1],[1,0]]), (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
print(np.unravel_index(99,(6,7,8))) 

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
np.tile(np.array([[0,1],[1,0]]), (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
arr = np.random.random((5,5))
arr = (arr - np.mean(arr))/(np.std(arr)) # делаем z - преобразование 
arr

array([[ 1.04142159, -1.48428969,  0.93575844, -1.48758854, -0.60010954],
       [ 0.17380466,  1.36293297, -1.41583508, -0.87556697,  0.00449641],
       [-0.15992408,  0.18403992, -0.47389681,  0.37669447, -0.50999575],
       [ 0.61435123,  0.29630228,  0.63226001,  1.08860412, -0.87264855],
       [-1.29926325,  1.3290641 ,  2.10373726,  0.45640121, -1.42075038]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
# хз 

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
np.random.random((5,3)) @ np.ones((3,2))

array([[1.27022009, 1.27022009],
       [1.77077551, 1.77077551],
       [1.91336665, 1.91336665],
       [1.17792234, 1.17792234],
       [1.88298928, 1.88298928]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
arr = np.arange(15)
np.array(list(map(lambda x: -x if x in np.arange(3, 9) else x, arr)))

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10, 11, 12, 13, 14])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

9
10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
# нельзя Z**Z Z<Z>Z 

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-165-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-165-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
arr = np.random.uniform(-15, 15, 15)
np.copysign(np.ceil(np.abs(arr)), arr)

array([ -5., -15.,  -6.,   6., -11.,   1.,  13.,  10.,  -6.,  -2.,  -2.,
       -12.,  -6.,  -8.,  10.])

#### 30. How to find common values between two arrays? (★☆☆)

In [4]:
arr1 = np.arange(-5, 5)
arr2 = np.arange(10)
np.intersect1d(arr1, arr2)

array([0, 1, 2, 3, 4])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [10]:
defaults = np.seterr(all="ignore")
arr = np.arange(10)
arr = arr / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

Нет, будут возвращены разные значения: nan и i (1j)

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [15]:
print(f"yesterday: {np.datetime64('today', 'D') - np.timedelta64(1, 'D')} , today: {np.datetime64('today', 'D')}, tomorrow: {np.datetime64('today', 'D') + np.timedelta64(1, 'D')}")

yesterday: 2022-12-24 , today: 2022-12-25, tomorrow: 2022-12-26


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [18]:
days = np.arange("2016-07", "2016-08", dtype="datetime64[D]")
print(days)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [27]:
A = np.eye(5) 
B = np.eye(5) 
np.add(A, B, out=B)
np.negative(A, out=A)
np.divide(A, 2, out=A)
np.multiply(A, B, out=A)

array([[-1., -0., -0., -0., -0.],
       [-0., -1., -0., -0., -0.],
       [-0., -0., -1., -0., -0.],
       [-0., -0., -0., -1., -0.],
       [-0., -0., -0., -0., -1.]])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [37]:
arr = np.random.normal(0, 10, 5)
print(np.floor(arr))
print(arr - arr%1)
print(arr // 1)
print(arr.astype(int))

[ 9.  9.  7.  1. -9.]
[ 9.  9.  7.  1. -9.]
[ 9.  9.  7.  1. -9.]
[ 9  9  7  1 -8]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [38]:
np.array([np.arange(5) for i in range(0, 5)])

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [42]:
def generator():
    for i in range(10):
        yield (i + 4 ) % 11
np.array([i for i in generator()])

array([ 4,  5,  6,  7,  8,  9, 10,  0,  1,  2])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [46]:
np.linspace(0.01,1,10,endpoint=False)

array([0.01 , 0.109, 0.208, 0.307, 0.406, 0.505, 0.604, 0.703, 0.802,
       0.901])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [48]:
np.sort(np.random.random(10))

array([0.16558616, 0.30150026, 0.37160832, 0.43919941, 0.77168362,
       0.78334247, 0.84186144, 0.95039966, 0.96673269, 0.98572534])

#### 41. How to sum a small array faster than np.sum? (★★☆)

idk

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [49]:
arr1 = np.random.random(10)
arr2 = np.random.random(10)
print(np.allclose(arr1,arr2))

False


#### 43. Make an array immutable (read-only) (★★☆)

In [240]:
arr = np.arange(10)
arr.flags.writeable = False
try: 
    arr[4] = 1
except ValueError:
    print('Ошибка: массив только для записи ')

Ошибка: массив только для записи 


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [241]:
v = np.array([[1,0],[1,1], [0,1], [-1,1], [-1,0], [-1,-1], [0,-1], [1,-1]]).astype(np.float64)
print(v)
print('=======')
x,y = v[:,0], v[:,1]
r = np.sqrt(x**2+y**2)
e = np.arctan2(y,x)
v[:,0] = r
v[:,1] = e
print(v)

[[ 1.  0.]
 [ 1.  1.]
 [ 0.  1.]
 [-1.  1.]
 [-1.  0.]
 [-1. -1.]
 [ 0. -1.]
 [ 1. -1.]]
[[ 1.     0.   ]
 [ 1.414  0.785]
 [ 1.     1.571]
 [ 1.414  2.356]
 [ 1.     3.142]
 [ 1.414 -2.356]
 [ 1.    -1.571]
 [ 1.414 -0.785]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [242]:
arr = np.random.randint(1,10, 10)
print( arr)
arr[arr.argmax()] = 0
print(arr)

[2 2 3 3 8 7 4 7 9 8]
[2 2 3 3 8 7 4 7 0 8]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [243]:
arr = np.zeros((3,3), [('x',float),('y',float)]) 
arr['x'], arr['y'] = np.meshgrid(np.linspace(0,1,3),
                             np.linspace(0,1,3))
print(arr)

[[(0. , 0. ) (0.5, 0. ) (1. , 0. )]
 [(0. , 0.5) (0.5, 0.5) (1. , 0.5)]
 [(0. , 1. ) (0.5, 1. ) (1. , 1. )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [245]:
X = np.arange(4)
print(X)

Y = X + 0.5
print(Y)

C = 1.0 / np.subtract.outer(X, Y)
print('Матрица Коши', C)
print('Определитель матрицы Коши', np.linalg.det(C))

[0 1 2 3]
[0.5 1.5 2.5 3.5]
Матрица Коши [[-2.    -0.667 -0.4   -0.286]
 [ 2.    -2.    -0.667 -0.4  ]
 [ 0.667  2.    -2.    -0.667]
 [ 0.4    0.667  2.    -2.   ]]
Определитель матрицы Коши 44.38416931216933


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [89]:
for dtype in [np.int8, np.int32, np.int64]:
   print(f'Тип: {dtype.__name__}, минимум: {np.iinfo(dtype).min}, максимум: {np.iinfo(dtype).max}')
for dtype in [np.float32, np.float64]:
   print(f'Тип: {dtype.__name__}, минимум: {np.finfo(dtype).min}, максимум: {np.finfo(dtype).max}')

Тип: int8, минимум: -128, максимум: 127
Тип: int32, минимум: -2147483648, максимум: 2147483647
Тип: int64, минимум: -9223372036854775808, максимум: 9223372036854775807
Тип: float32, минимум: -3.4028234663852886e+38, максимум: 3.4028234663852886e+38
Тип: float64, минимум: -1.7976931348623157e+308, максимум: 1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [246]:
print('Значение порога по умолчанию:', np.get_printoptions()['threshold'])
arr = np.zeros((26,100))
print('Вывод нулевого массива 26 на 100', arr)
np.set_printoptions(threshold=float("inf"))  # снять ограничения 
print('Вывод нулевого массива 26 на 100 без ограничений вывода:\n', arr)

Значение порога по умолчанию: inf
Вывод нулевого массива 26 на 100 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [249]:
v = np.arange(20)
print(v)

a = np.random.uniform(low=0,high=20)
index = (np.abs(v-a)).argmin()
print(f'Ближайшее значение в векторе к значению {a} = {v[index]}')

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Ближайшее значение в векторе к значению 13.584030014747563 = 14


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [252]:
type_scalar = np.dtype('float32')

array_type = np.dtype([('position', 
                            [('x', type_scalar),
                             ('y', type_scalar)]),
                        ('color', 
                            [('r', type_scalar),
                             ('g', type_scalar),
                             ('b', type_scalar)])
                        ])
arr = np.zeros(2,  array_type)    
arr[0] = ((10., 50.), (255., 0., 255.))
arr[1] = ((20., 30.), (51., 230., 255.))
print(arr)


[((10., 50.), (255.,   0., 255.)) ((20., 30.), ( 51., 230., 255.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [253]:
N = 100  
arr = np.random.random((N,2))
print(arr)

x,y = np.atleast_2d(arr[:,0], arr[:,1])
dist = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
print(dist)

[[0.552 0.926]
 [0.197 0.466]
 [0.922 0.543]
 [0.383 0.485]
 [0.382 0.023]
 [0.239 0.039]
 [0.105 0.561]
 [0.711 0.618]
 [0.384 0.291]
 [0.948 0.871]
 [0.734 0.754]
 [0.069 0.058]
 [0.254 0.091]
 [0.643 0.713]
 [0.035 0.946]
 [0.437 0.342]
 [0.822 0.924]
 [0.35  0.368]
 [0.22  0.126]
 [0.224 1.   ]
 [0.832 0.867]
 [0.987 0.409]
 [0.388 0.96 ]
 [0.615 0.253]
 [0.97  0.894]
 [0.254 0.89 ]
 [0.967 0.694]
 [0.831 0.213]
 [0.011 0.449]
 [0.356 0.435]
 [0.698 0.328]
 [0.008 0.047]
 [0.442 0.205]
 [0.143 0.537]
 [0.617 0.652]
 [0.97  0.122]
 [0.777 0.432]
 [0.476 0.756]
 [0.55  0.492]
 [0.308 0.887]
 [0.832 0.488]
 [0.415 0.224]
 [0.266 0.047]
 [0.401 0.268]
 [0.198 0.613]
 [0.556 0.344]
 [0.546 0.804]
 [0.985 0.569]
 [0.567 0.641]
 [0.29  0.403]
 [0.622 0.449]
 [0.114 0.487]
 [0.155 0.296]
 [0.987 0.097]
 [0.867 0.172]
 [0.229 0.842]
 [0.559 0.469]
 [0.788 0.308]
 [0.216 0.166]
 [0.399 0.896]
 [0.067 0.411]
 [0.356 0.912]
 [0.903 0.059]
 [0.055 0.144]
 [0.642 0.581]
 [0.393 0.67 ]
 [0.756 0.

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [127]:
float_n = (np.random.rand(1)*100).astype(np.float32)
print(float_n[0])
int_n = float_n.view(np.int32) 
int_n[:] = float_n 
print(int_n[0])

72.981735
72


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [128]:
from io import StringIO
input = StringIO('''
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
''')
print(np.genfromtxt(input, delimiter=","))

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [138]:
arr = np.eye(2)
 
for item in np.ndenumerate(arr):
    print(item[0], item[1])
for index_of_value in np.ndindex(arr.shape):
    print(index_of_value, arr[index_of_value])

(0, 0) 1.0
(0, 1) 0.0
(1, 0) 0.0
(1, 1) 1.0
(0, 0) 1.0
(0, 1) 0.0
(1, 0) 0.0
(1, 1) 1.0


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [258]:
sigma, mu = 1.0, 2.0
A, B = np.meshgrid(np.linspace(-1,1,4), np.linspace(-1,1,4))
distrib = np.sqrt(A*A+B*B)
denom = 2.0 * sigma**2
print(np.exp(-((distrib-mu)**2 /denom)))

[[0.842 0.639 0.639 0.842]
 [0.639 0.311 0.311 0.639]
 [0.639 0.311 0.311 0.639]
 [0.842 0.639 0.639 0.842]]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [149]:
p = 6
arr = np.ones((5,5)) 
indexes = np.random.choice(arr.size, p, replace=False)
np.put(arr, indexes, p)
print(arr)

[[6. 1. 6. 1. 1.]
 [1. 1. 1. 6. 6.]
 [6. 1. 1. 1. 1.]
 [1. 1. 1. 6. 1.]
 [1. 1. 1. 1. 1.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [153]:
arr = np.random.randint(0,100,25).reshape(5, 5)

print(arr)

new_arr = arr - arr.mean(axis=1, keepdims=True)
print(new_arr)

[[13  4 95 83 51]
 [11 51 97 30 20]
 [28 84 85 41 39]
 [ 9 34 18 41 43]
 [63 15  5 62 27]]
[[-36.2 -45.2  45.8  33.8   1.8]
 [-30.8   9.2  55.2 -11.8 -21.8]
 [-27.4  28.6  29.6 -14.4 -16.4]
 [-20.    5.  -11.   12.   14. ]
 [ 28.6 -19.4 -29.4  27.6  -7.4]]


#### 59. How to sort an array by the nth column? (★★☆)

In [160]:
n=2
arr = np.random.randint(0,10,16).reshape(4,4)
print(arr)
arr = arr[arr[:,2].argsort()]
print(arr) 

[[3 3 4 8]
 [1 3 3 6]
 [9 8 8 7]
 [0 1 3 3]]
[[1 3 3 6]
 [0 1 3 3]
 [3 3 4 8]
 [9 8 8 7]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [167]:
arr = np.random.randint(0,2,9).reshape(3,3)
print(arr)
print((~arr.any(axis=0)).any())

[[0 1 0]
 [0 0 1]
 [0 1 0]]
True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [171]:
arr = np.arange(10).reshape(2,5)
print(arr)

a = np.random.uniform(low=0,high=10)
index = (np.abs(arr-a)).argmin()
print(f'Ближайшее значение в векторе к ({a}):= {arr.flat[index]}')

[[0 1 2 3 4]
 [5 6 7 8 9]]
Ближайшее значение в векторе к (0.5495339221719031):= 1


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [172]:
X = np.arange(3).reshape(1,3)
Y = np.arange(3).reshape(3,1)
iterator = np.nditer([X,Y,None])
for x,y,res in iterator:
    res[...] = x + y
print(iterator.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [180]:
class Name(np.ndarray):
    def __new__(p, array, name="blank"):
        obj = np.asarray(array).view(p)
        obj.name = name
        return obj

arr = Name(np.random.randint(2,8,4))
arr.name = 'arr'
print (arr.name, arr, type(arr))

arr [4 6 2 3] <class '__main__.Name'>


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [186]:
arr = np.zeros(5)
I = np.random.randint(1,5-1,5*2)
arr += np.bincount(I, minlength=len(arr))
print(arr)

[0. 4. 4. 2. 0.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [210]:
I = [2,4,6,1]
F = np.bincount(I,np.random.randint(1,9,4))
print(F)

[0. 3. 2. 0. 6. 0. 2.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [222]:
w = 256
h = 16 
matrix = np.random.randint(0, 8, (w, h, 3)).astype(np.ubyte)
unique_col = np.unique(matrix.reshape(-1,3), axis = 0)
print(len(unique_col))


512


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [226]:
matrix = np.random.randint(0, 8, (2,3,4,2))
print(matrix)
print("==========")
print(matrix.sum(axis=(-2,-1)))

[[[[0 5]
   [1 1]
   [1 4]
   [0 2]]

  [[5 3]
   [6 6]
   [3 3]
   [7 5]]

  [[5 6]
   [7 6]
   [2 7]
   [2 2]]]


 [[[3 0]
   [6 3]
   [6 4]
   [3 0]]

  [[7 5]
   [7 4]
   [7 7]
   [4 5]]

  [[3 4]
   [6 6]
   [6 0]
   [0 7]]]]
[[14 38 37]
 [25 46 32]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [268]:
A = np.random.uniform(0,1,50)
B = np.random.randint(0,5,50)
print(np.bincount(B, A)/ np.bincount(B))

[0.465 0.463 0.479 0.544 0.538]


#### 69. How to get the diagonal of a dot product? (★★★)

In [191]:
A = np.random.randint(1,9,4).reshape(2,2)
B = np.random.randint(10,15, 4).reshape(2,2)
print(A, B, sep='\n')
print(np.diag(A @ B))

[[4 4]
 [8 5]]
[[11 10]
 [14 11]]
[100 135]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [228]:
v = np.array([1,2,3,4,5])
v_vs_pad = np.zeros(4*len(v)- 3)
v_vs_pad[::3+1] = v
print(v_vs_pad)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [206]:
A = np.random.randint(1,9,5*5*3).reshape(5,5,3)
B = np.random.randint(1,9,5*5).reshape(5,5)
#нЕ ДОДЕЛАЛ

#### 72. How to swap two rows of an array? (★★★)

In [193]:
A = np.random.randint(1,9,4).reshape(2,2)
print(A)
A[[0,1]] = A[[1,0]]
print(A)

[[3 5]
 [6 6]]
[[6 6]
 [3 5]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [234]:
C = np.bincount([1,1,2,2,3,4])
Filler = np.arange(len(C))
A = np.repeat(Filler, C)
print(A)

[1 1 2 2 3 4]


#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [208]:
arr = np.random.randint(0,2,10)
print(arr)
print(np.logical_not(arr, out=arr))

arr2 = np.random.uniform(-3.0,3.0,10)
print(arr2)
print(np.negative(arr2, out=arr2))

[0 0 0 0 1 1 0 1 1 1]
[1 1 1 1 0 0 1 0 0 0]
[-2.13  -2.475 -1.459  0.841  0.418  2.336  2.509 -2.086 -2.286 -2.94 ]
[ 2.13   2.475  1.459 -0.841 -0.418 -2.336 -2.509  2.086  2.286  2.94 ]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

In [195]:
A = np.random.randint(1,19,16).reshape(4,4)
print(A)
np.linalg.matrix_rank(A)

[[ 7  8  4  5]
 [ 6 15  7  6]
 [10 14 15  4]
 [16 12  7  3]]


4

#### 83. How to find the most frequent value in an array?

In [203]:
A = np.random.randint(1,9,7)
print(A)
print(np.bincount(A).argmax())

[3 4 1 7 8 8 2]
8


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [269]:
X = np.random.randn(100)
index = np.random.randint(0, X.size, (100, X.size))
mean_v = X[index].mean(axis=1)
interval = np.percentile(mean_v, [2.5, 97.5])
print(interval)

[-0.203  0.198]
